{{- if .Values.security.networkPolicy.enabled -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "library-chart.fullname" . }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  ingress:
  - from:
    - podSelector: {}
  policyTypes:
  - Ingress
{{- end }}
